version: "3.4"

services:
  yacobooks-front:
    container_name: yacobooks-front
    build:
      context: .
    expose:
      - 5000
    
  nginx:
    container_name: yacobooks-proxy
    build:
      context: nginx
    ports:
      - "80:80"
    depends_on:
      - yacobooks-front

networks:
  default:
    external:
      name: yaco_net